"""Write dbt's `profiles.yml` from DATABASE_URL.

    python -m pipeline.db.dbt_profile

dbt wants host, user, password and dbname as separate fields; the rest of the project
keeps one connection string in `.env`. Deriving one from the other means the credentials
are written down once. The generated file holds a password, so it is gitignored and
rewritten rather than edited.
"""

from __future__ import annotations

from pathlib import Path
from urllib.parse import unquote, urlsplit

from pipeline.config import require_env

PROFILE_NAME = "job_insight"
SCHEMA = "analytics"
"""Everything dbt builds lands here; `raw` stays untouched. Models are told apart by name
(`stg_`, `int_`, `mart_`), which at this size is clearer than a schema per layer."""

PROFILES_PATH = Path(__file__).resolve().parents[1] / "dbt" / "profiles.yml"

TEMPLATE = """# Generated by `python -m pipeline.db.dbt_profile` - do not edit, do not commit.
{name}:
  target: prod
  outputs:
    prod:
      type: postgres
      host: {host}
      port: {port}
      user: {user}
      password: {password}
      dbname: {dbname}
      schema: {schema}
      sslmode: require
      threads: 4
      keepalives_idle: 0
"""


def render(database_url: str) -> str:
    """The profiles.yml contents for one connection string."""
    parts = urlsplit(database_url)
    if not parts.hostname or not parts.username:
        raise ValueError("DATABASE_URL is missing a host or user")
    return TEMPLATE.format(
        name=PROFILE_NAME,
        host=parts.hostname,
        port=parts.port or 5432,
        user=unquote(parts.username),
        password=unquote(parts.password or ""),
        dbname=(parts.path or "/postgres").lstrip("/"),
        schema=SCHEMA,
    )


def main() -> None:
    PROFILES_PATH.parent.mkdir(parents=True, exist_ok=True)
    PROFILES_PATH.write_text(render(require_env("DATABASE_URL")), encoding="utf-8")
    print(f"wrote {PROFILES_PATH}")


if __name__ == "__main__":
    main()
